#!/usr/bin/env node
// Extracts the Material Symbols (Apache-2.0, rounded, weight 400) the UI uses into a small
// TS module, so the app ships ~150 icons instead of the 7,800-icon font.
// Run: node scripts/gen-icons.mjs
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const NAMES = `
menu close arrow_back arrow_forward search my_location location_searching location_disabled navigation explore layers
directions turn_right near_me call public schedule location_on share bookmark star home work history
tram subway directions_railway departure_board add remove trending_up trending_down elevation airport_shuttle gondola_lift commute rss_feed directions_subway do_not_disturb_on update
restaurant local_cafe shopping_cart local_gas_station ev_station local_pharmacy local_atm local_parking hotel
photo_camera park local_hospital directions_car directions_walk directions_bike directions_railway swap_vert
more_vert add delete edit download upload link settings flag lock mobile_arrow_down volume_up volume_off sports_score
accessible content_copy keyboard_arrow_down keyboard_arrow_up play_arrow trip_origin info mail open_in_new image map satellite_alt
landscape_2 train view_in_ar add_location_alt edit_location_alt person check refresh chevron_left chevron_right
arrow_upward north turn_left turn_slight_left turn_slight_right turn_sharp_left turn_sharp_right u_turn_left
u_turn_right roundabout_right roundabout_left merge fork_right fork_left ramp_right ramp_left directions_boat
local_mall museum school church synagogue mosque account_balance local_bar fastfood bakery_dining grocery
storefront fitness_center content_cut spa local_laundry_service apartment business_center gavel theater_comedy
movie palette beach_access attractions pets sports_soccer pool stadium local_police local_post_office
local_library local_fire_department medication dentistry medical_services directions_bus flight car_repair
car_rental local_florist checkroom diamond devices construction warehouse factory celebration nightlife castle
landscape water luggage home_repair_service real_estate_agent hiking wc icecream sports_bar liquor local_drink
toys music_note book_2 nature_people cottage camping golf_course playground child_care hearing visibility
emergency volunteer_activism groups account_circle bookmarks photo_library rate_review add_a_photo feedback
mode_of_travel route alt_route tune event filter_list dark_mode light_mode language straighten
keyboard undo
`.trim().split(/\s+/);
// Icons drawn filled (selected / solid look), as Google does for these.
const FILLED = new Set(['navigation', 'location_on', 'bookmark', 'star', 'home', 'work', 'directions', 'trip_origin', 'explore', 'person', 'account_circle', 'bookmarks']);

const dir = join(process.cwd(), 'node_modules/@material-symbols/svg-400/rounded');
const out = {};
const missing = [];
for (const n of [...new Set(NAMES)].sort()) {
  const variants = FILLED.has(n) ? [[n, `${n}-fill`], [`${n}_outline`, n]] : [[n, n]];
  for (const [key, file] of variants) {
    const path = join(dir, `${file.replace(/_/g, '_')}.svg`);
    if (!existsSync(path)) {
      missing.push(file);
      continue;
    }
    const svg = readFileSync(path, 'utf8');
    const ds = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);
    if (!ds.length) throw new Error(`${file}: no path`);
    out[key] = ds.join(' ');
  }
}
if (missing.length) {
  console.error('missing:', missing.join(' '));
  process.exit(1);
}
writeFileSync(
  'packages/core/src/app/icon-paths.ts',
  `// Generated by scripts/gen-icons.mjs from @material-symbols/svg-400 (Apache-2.0). Do not edit.\n// Path data in a "0 -960 960 960" viewBox.\nexport const ICONS: Record<string, string> = ${JSON.stringify(out, null, 0).replace(/","/g, '",\n  "')};\n`,
);
console.log(`wrote ${Object.keys(out).length} icons`);
