#!/usr/bin/env node
// Extracts the Maki (CC0) icon paths the base map uses into a small TS module,
// so the app ships only the ~60 icons it draws instead of all 200+.
// Run: node --experimental-strip-types scripts/gen-maki.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { poiImageList } from '../apps/web/src/shell/basemap/poi.ts';

const require = createRequire(join(process.cwd(), 'apps/web/package.json'));
const dir = join(dirname(require.resolve('@mapbox/maki/package.json')), 'icons');
const names = new Set([...poiImageList('light').map((i) => i.icon).filter(Boolean), 'mountain']);
const out = {};
for (const n of [...names].sort()) {
  const svg = readFileSync(join(dir, `${n}.svg`), 'utf8');
  if (/transform=|<(circle|rect|polygon|ellipse|g )/.test(svg)) throw new Error(`${n}: only plain paths are supported`);
  const ds = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) =>
    m[1].replace(/&#xA;|&#x9;|\s+/g, ' ').trim(),
  );
  if (!ds.length) throw new Error(`${n}: no path`);
  out[n] = ds.join(' ');
}
writeFileSync(
  'apps/web/src/shell/basemap/maki-paths.ts',
  `// Generated by scripts/gen-maki.mjs from @mapbox/maki (CC0). Do not edit.\n// 15x15 SVG path data per icon.\nexport const MAKI: Record<string, string> = ${JSON.stringify(out, null, 2)};\n`,
);
console.log(`wrote ${Object.keys(out).length} icons`);
